export enum DISTRIBUTION_TYPE {
  FOOD = 'food',
  ENERGY = 'energy',
  TAXES = 'taxes',
  HOUSE = 'house'
}

export const DISTRIBUTION_DEFAULT_VALUES = {
  [DISTRIBUTION_TYPE.FOOD]: 4,
  [DISTRIBUTION_TYPE.ENERGY]: 4,
  [DISTRIBUTION_TYPE.TAXES]: 50,
  [DISTRIBUTION_TYPE.HOUSE]: 1
};

export const DISTRIBUTION_MIN_VALUES = {
  [DISTRIBUTION_TYPE.FOOD]: 1,
  [DISTRIBUTION_TYPE.ENERGY]: 1,
  [DISTRIBUTION_TYPE.TAXES]: 1,
  [DISTRIBUTION_TYPE.HOUSE]: 1
};

export const DISTRIBUTION_MAX_VALUES = {
  [DISTRIBUTION_TYPE.FOOD]: 99999,
  [DISTRIBUTION_TYPE.ENERGY]: 99999,
  [DISTRIBUTION_TYPE.TAXES]: 9999,
  [DISTRIBUTION_TYPE.HOUSE]: 1
};
