packages:
  - packages/**

catalog:
  '@commitlint/cli': 20.1.0
  '@commitlint/config-conventional': 20.0.0
  '@fullhuman/postcss-purgecss': 7.0.2
  '@js-basics/vector': 2.2.5
  '@nuxt/eslint': 1.10.0
  '@nuxtjs/critters': 0.9.0
  '@nuxtjs/robots': 5.5.6
  '@nuxtjs/sitemap': 7.4.7
  '@types/columnify': 1.5.4
  '@types/file-saver': 2.0.7
  '@types/node': 24.10.1
  '@types/web': 0.0.294
  change-case: 5.4.4
  columnify: 1.6.0
  coi-serviceworker: 0.1.7
  consola: 3.4.2
  dotenv-mono: 1.5.1
  eslint: 9.39.1
  eslint-config-prettier: 10.1.8
  eslint-plugin-prettier: 5.5.4
  eslint-plugin-security: 3.0.1
  file-saver: 2.0.5
  firebase: 12.6.0
  husky: 9.1.7
  jszip: 3.10.1
  lint-staged: 16.2.7
  marked: 16.4.2
  marked-mangle: 1.1.12
  nuxt: 4.2.0
  pathe: 2.0.3
  postcss-html: 1.8.0
  postcss-nested: 7.0.2
  postcss-normalize: 13.0.1
  postcss-preset-env: 10.4.0
  postcss-url: 10.1.3
  prettier: 3.6.2
  range-overlap: 1.0.0
  read-pkg: 9.0.1
  rucksack-css: 1.0.2
  rxjs: 7.8.2
  stylelint: 16.26.0
  stylelint-config-css-modules: 4.5.1
  stylelint-config-recess-order: 7.4.0
  stylelint-config-standard: 39.0.1
  stylelint-prettier: 5.0.3
  three: 0.181.2
  '@types/three': 0.181.0
  tsx: 4.20.6
  typescript: 5.9.3
  typescript-eslint: 8.47.0
  '@typescript-eslint/eslint-plugin': 8.47.0
  ufo: 1.6.1
  vite: 7.2.4
  vite-plugin-checker: 0.11.0
  vite-plugin-markdown: 2.2.0
  vite-plugin-mkcert: 1.17.9
  vite-plugin-node-polyfills: 0.24.0
  vite-plugin-eslint2: 5.0.4
  vite-svg-loader: 5.1.0
  vitest: 4.0.13
  vue: 3.5.24
  vue-eslint-parser: 10.2.0
  vue-tsc: 3.1.4

onlyBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - canvas
  - esbuild
  - protobufjs
  - unrs-resolver
  - wasm-pack
