packages:
  - packages/**

catalog:
  '@commitlint/cli': 19.8.1
  '@commitlint/config-conventional': 19.8.1
  '@fullhuman/postcss-purgecss': 7.0.2
  '@js-basics/vector': 2.2.5
  '@nuxt/eslint': 1.8.0
  '@nuxtjs/critters': 0.9.0
  '@nuxtjs/robots': 5.4.0
  '@nuxtjs/sitemap': 7.4.3
  '@types/columnify': 1.5.4
  '@types/file-saver': 2.0.7
  '@types/node': 24.3.0
  '@types/web': 0.0.262
  change-case: 5.4.4
  columnify: 1.6.0
  coi-serviceworker: 0.1.7
  consola: 3.4.2
  dotenv-mono: 1.5.0
  eslint: 9.33.0
  eslint-config-prettier: 10.1.8
  eslint-plugin-prettier: 5.5.4
  eslint-plugin-security: 3.0.1
  file-saver: 2.0.5
  firebase: 12.1.0
  husky: 9.1.7
  jszip: 3.10.1
  lint-staged: 16.1.5
  marked: 16.1.2
  marked-mangle: 1.1.11
  nuxt: 4.0.3
  pathe: 2.0.3
  postcss-html: 1.8.0
  postcss-nested: 7.0.2
  postcss-normalize: 13.0.1
  postcss-preset-env: 10.2.4
  postcss-url: 10.1.3
  prettier: 3.6.2
  range-overlap: 1.0.0
  read-pkg: 9.0.1
  rucksack-css: 1.0.2
  rxjs: 7.8.2
  stylelint: 16.23.1
  stylelint-config-css-modules: 4.5.1
  stylelint-config-recess-order: 7.2.0
  stylelint-config-standard: 39.0.0
  stylelint-prettier: 5.0.3
  three: 0.179.1
  '@types/three': 0.179.0
  tsx: 4.20.4
  typescript: 5.9.2
  typescript-eslint: 8.39.1
  '@typescript-eslint/eslint-plugin': 8.39.1
  ufo: 1.6.1
  vite: 7.1.2
  vite-plugin-checker: 0.10.2
  vite-plugin-markdown: 2.2.0
  vite-plugin-mkcert: 1.17.8
  vite-plugin-node-polyfills: 0.24.0
  vite-plugin-eslint2: 5.0.4
  vite-svg-loader: 5.1.0
  vitest: 3.2.4
  vue: 3.5.18
  vue-eslint-parser: 10.2.0
  vue-tsc: 3.0.5

onlyBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - canvas
  - esbuild
  - protobufjs
  - unrs-resolver
  - wasm-pack
