packages:
  - 'packages/**'
catalog:
    '@commitlint/cli': '19.8.0'
    '@commitlint/config-conventional': '19.8.0'
    '@fullhuman/postcss-purgecss': '7.0.2'
    '@js-basics/vector': 'https://pkg.pr.new/basics/vector/@js-basics/vector@003b2ae'
    '@nuxt/eslint': '1.3.0'
    '@nuxtjs/critters': '0.9.0'
    '@nuxtjs/robots': '5.2.10'
    '@nuxtjs/sitemap': '7.2.10'
    '@types/columnify': '1.5.4'
    '@types/node': '22.15.2'
    '@types/web': '0.0.76'
    'change-case': '5.4.4'
    'columnify': '1.6.0'
    'dotenv-mono': '1.3.14'
    'eslint': '9.25.1'
    'eslint-config-prettier': '10.1.2'
    'eslint-plugin-prettier': '5.2.6'
    'eslint-plugin-security': '3.0.1'
    'file-saver': '2.0.5'
    'firebase': '11.6.1'
    'husky': '9.1.7'
    'lint-staged': '15.5.1'
    'marked': '15.0.11'
    'marked-mangle': '1.1.10'
    'nuxt': '3.16.2'
    'pathe': '2.0.3'
    'postcss-html': '1.8.0'
    'postcss-nested': '7.0.2'
    'postcss-normalize': '13.0.1'
    'postcss-preset-env': '10.1.6'
    'postcss-url': '10.1.3'
    'prettier': '3.5.3'
    'range-overlap': '1.0.0'
    'read-pkg': '9.0.1'
    'rucksack-css': '1.0.2'
    'rxjs': '7.8.2'
    'stylelint': '16.19.1'
    'stylelint-config-css-modules': '4.4.0'
    'stylelint-config-recess-order': '6.0.0'
    'stylelint-config-standard': '38.0.0'
    'stylelint-prettier': '5.0.3'
    'tone': '15.0.4'
    'tsx': '4.19.3'
    'typescript': '5.8.3'
    'typescript-eslint': '8.31.0'
    'uuid': '11.1.0'
    'ufo': '1.6.1'
    'vite': '6.3.3'
    'vite-plugin-checker': '0.9.1'
    'vite-plugin-markdown': '2.2.0'
    'vite-plugin-mkcert': '1.17.8'
    'vite-plugin-node-polyfills': '0.23.0'
    'vite-svg-loader': '5.1.0'
    'vitest': '3.1.2'
    'vue': '3.5.13'
    'vue-eslint-parser': '10.1.3'
    'vue-tsc': '2.2.10'
    'webmidi': '3.1.12'
onlyBuiltDependencies:
  - '@firebase/util'
  - '@parcel/watcher'
  - 'esbuild'
  - 'protobufjs'
  - 'unrs-resolver'
