export enum TYPE {
  DEFAULT = 'default',
  LINK = 'link',
  CLOUD_DISK = 'cloud_disk',
  FLOPPY_DISK = 'floppy_disk',
  HARD_DISK = 'hard_disk',
  RAM_DISK = 'ram_disk',
  TMP_DISK = 'tmp_disk',
  DIRECTORY = 'directory',
  FILE = 'file',
  TRASHCAN = 'trashcan',
  DISK = 'disk',
  VIEW = 'view'
}

export enum SYMBOL {
  DEFAULT = 'default',
  DIRECTORY = 'directory',
  DIRECTORY_PREFS = 'directory_prefs',
  CLOUD_DISK = 'cloud_disk',
  HARD_DISK = 'hard_disk',
  RAM_DISK = 'ram_disk',
  TMP_DISK = 'tmp_disk',
  DISK_1 = 'disk_1',
  DISK_2 = 'disk_2',
  DISK_WORKBENCH13 = 'disk_workbench13',
  DISK_MARKDOWN = 'disk_markdown',
  DISK_BASIC = 'disk_basic',
  WORK = 'work',
  CONSOLE = 'console',
  SETTINGS = 'settings',
  TRASHCAN = 'trashcan',
  COMPUTER_1 = 'computer_1',
  TELEPHONE = 'telephone',
  CURSOR = 'cursor',
  PREFERENCE = 'preference',
  WEB_BASIC = 'web_basic',
  WEB_PAINTING = 'web_painting',
  COLORS = 'colors',
  PRINT_1 = 'print_1',
  PRINT_2 = 'print_2',
  NOTEPAD = 'notepad',
  BASIC = 'basic',
  IMAGE = 'image',
  NOTE = 'note',
  NOTE_BLANK = 'note_blank',
  LARGE_NOTE = 'large_note',
  LARGE_NOTE_RICH = 'large_note_rich',
  FULLSCREEN = 'fullscreen',
  CALCULATOR = 'calculator',
  CLOCK = 'clock',
  KEYBOARD_QUESTION = 'keyboard_question',
  LARGE_NOTEPAD = 'large_notepad',
  LARGE_NOTEPAD_HELP = 'large_notepad_help',
  RABBIT = 'rabbit',
  MORE = 'more',
  SAY = 'say',
  GITHUB = 'github',
  LAMMPEE = 'lammpee',
  CUBY = 'cuby',
  NUXT = 'nuxt',
  CLOWN = 'clown',
  DISALLOW_1 = 'disallow_1',
  COPY_1 = 'copy_1',
  COPY_2 = 'copy_2',
  DISPLAY_KEYBOARD = 'display_keyboard',
  PALETTE = 'palette',
  SIGN_1 = 'sign_1',
  DOCUMENT_EDITOR = 'document_editor',
  DOCUMENT_READER = 'document_reader',
  SYNTHESIZER = 'synthesizer',
  VUE_SEMANTIC_STRUCTURE = 'vue_semantic_structure',
  NUXT_BOOSTER = 'nuxt_booster',
  MOON_CITY = 'moon_city',
  GUEST_BOOK = 'guest_book'
}

export enum SYMBOL_TYPE {
  DEFAULT = 0,
  SVG = 1,
  IMG = 2
}
