export const TYPE = {
  DEFAULT: 'default',
  LINK: 'link',
  CLOUD_DISK: 'cloud_disk',
  FLOPPY_DISK: 'floppy_disk',
  HARD_DISK: 'hard_disk',
  RAM_DISK: 'ram_disk',
  TMP_DISK: 'tmp_disk',
  DIRECTORY: 'directory',
  FILE: 'file',
  TRASHCAN: 'trashcan',
  DISK: 'disk',
  VIEW: 'view'
};

export const SYMBOL = {
  DEFAULT: 'default',
  DIRECTORY: 'directory',
  DIRECTORY_PREFS: 'directory_prefs',
  CLOUD_DISK: 'cloud_disk',
  HARD_DISK: 'hard_disk',
  RAM_DISK: 'ram_disk',
  TMP_DISK: 'tmp_disk',
  DISK_1: 'disk_1',
  DISK_2: 'disk_2',
  DISK_WORKBENCH13: 'disk_workbench13',
  DISK_MARKDOWN: 'disk_markdown',
  DISK_BASIC: 'disk_basic',
  WORK: 'work',
  CONSOLE: 'console',
  SETTINGS: 'settings',
  TRASHCAN: 'trashcan',
  WEB_BASIC: 'web_basic',
  WEB_PAINTING: 'web_painting',
  COLORS: 'colors',
  PRINT_1: 'print_1',
  PRINT_2: 'print_2',
  NOTEPAD: 'notepad',
  BASIC: 'basic',
  IMAGE: 'image',
  NOTE: 'note',
  NOTE_BLANK: 'note_blank',
  FULLSCREEN: 'fullscreen',
  CALCULATOR: 'calculator',
  CLOCK: 'clock',
  KEYBOARD_QUESTION: 'keyboard_question',
  LARGE_NOTEPAD: 'large_notepad',
  RABBIT: 'rabbit',
  MORE: 'more',
  SAY: 'say',
  GITHUB: 'github',
  LAMMPEE: 'lammpee',
  CLOWN: 'clown',
  DISALLOW_1: 'disallow_1',
  DISK_COPY: 'disk_copy',
  DISPLAY_KEYBOARD: 'display_keyboard',
  PALETTE: 'palette',
  SIGN_1: 'sign_1'
};

export const SYMBOL_TYPE = {
  DEFAULT: 0,
  SVG: 1,
  IMG: 2
};
