export enum WINDOW_POSITION {
  CENTER = 0,
  ORDER_HORIZONTAL = 1,
  ORDER_VERTICAL = 2,
  ORDER_DIAGONAL_LEFT = 3,
  ORDER_DIAGONAL_RIGHT = 4,
  SPLIT_HORIZONTAL = 5,
  SPLIT_VERTICAL = 6
}

export enum CONFIG_NAMES {
  SHOW_STORAGE_SPACE = 'windowsShowStorageSpace'
}

export const CONFIG_DEFAULTS = {
  [CONFIG_NAMES.SHOW_STORAGE_SPACE]: true
};
