name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build (GH-Pages)
        run: |
          mkdir -p Ordner/{ghpages,firebase}
          npm run static
          touch dists/ghpages/.nojekyll
        env:
          BASE_PATH: /web-workbench/
          DIST_PATH: dists/ghpages
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
      # Firebase
      - name: Build (Firebase)
        run: |
          mkdir dists/firebase
          npm run static
        env:
          DIST_PATH: dists/firebase
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dists
          path: dists

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dists
          path: dists
      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dists/ghpages
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          PROJECT_PATH: dists/firebase
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
