name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout Repo
        uses: actions/checkout@master

      - name: cache node_modules
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Test
        run: npm run test

      # Build files for GH-Pages and Firebase

      # Github Pages
      - name: Build (GH-Pages)
        run: |
          mkdir -p dists/ghpages
          npm run static
          touch dists/ghpages/.nojekyll
        env:
          PWA_CACHE_VERSION: ${{ github.run_id }}
          HOST: https://thornwalli.github.io/web-workbench
          BASE_PATH: /web-workbench/
          DIST_PATH: dists/ghpages
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}

      # Firebase
      - name: Build (Firebase)
        run: |
          mkdir -p dists/firebase
          npm run static
          cp firebase.json dists/firebase/firebase.json
          cp .firebaserc dists/firebase/.firebaserc
        env:
          PWA_CACHE_VERSION: ${{ github.run_id }}
          HOST: https://lammpee.de
          DIST_PATH: dists/firebase
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_URL: ${{ secrets.FIREBASE_URL }}

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dists
          path: dists

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm i semantic-release @semantic-release/exec @semantic-release/git @semantic-release/changelog --no-save
          npx semantic-release --provider=github

  deploy:
    name: Deploy
    needs: build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dists
          path: dists
      - name: Deploy to GH-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: dists/ghpages
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          PROJECT_PATH: dists/firebase
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
